// Deposit money into John Doe's account
POST http://localhost:8083/api/transactions/deposit HTTP/1.1
Content-Type: application/json

{
    "accountId": "b914ac47-ed17-4582-8c35-76706b967acc",
    "typeOfTransaction": "DEPOSIT",
    "amount": 100.00
}


###

// Withdraw money from John Doe's account
POST http://localhost:8083/api/transactions/withdraw HTTP/1.1
Content-Type: application/json

{
    "accountId": "b914ac47-ed17-4582-8c35-76706b967acc",
    "typeOfTransaction": "WITHDRAWAL",
    "amount": 50.00
}

###

// Get the last 10 transactions of John Doe's account
GET http://localhost:8083/api/transactions/accounts/b914ac47-ed17-4582-8c35-76706b967acc/transactions HTTP/1.1

###

// Deposit money into Jane Smith's account
POST http://localhost:8083/api/transactions/deposit HTTP/1.1
Content-Type: application/json

{
    "accountId": "d21eb9d3-86be-4174-ab17-929a28bd2af8",
    "typeOfTransactionType": "DEPOSIT",
    "amount": 200.00
}

###
